driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
  - name: debian-8.5
  - name: freebsd-9.3
    run_list: freebsd::portsnap
  - name: freebsd-10.3
    run_list: freebsd::portsnap
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-chef-12.1
    driver_config:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12.1.0

suites:
  - name: default
    run_list:
      - recipe[test::default]
    excludes:
      - opensuse-13.2 # lacks nginx package
  - name: source
    run_list:
      - recipe[test::source]
    excludes:
      - ubuntu-16.04-chef-12.1
  - name: upstream_repo
    run_list:
      - recipe[test::upstream_repo]
    excludes:
      - fedora-24 # lacks nginx repo
      - ubuntu-16.04-chef-12.1
  - name: modules
    run_list:
      - recipe[test::modules]
    excludes:
      - ubuntu-16.04-chef-12.1
